name: Django CI/CD con Render

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del cÃ³digo
      uses: actions/checkout@v3

    - name: Crear archivo .env para pruebas
      run: |
        echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
        echo "DEBUG=True" >> .env
        echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
        echo "DB_ENGINE=django.db.backends.postgresql" >> .env
        echo "DB_NAME=postgres" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_HOST=db" >> .env
        echo "DB_PORT=5432" >> .env

    - name: Levantar Docker Compose
      run: docker compose up -d --build

    - name: Esperar a la base de datos
      run: sleep 10

    - name: Ejecutar migraciones
      run: docker compose exec -T web python manage.py migrate

    - name: Correr Tests
      run: docker compose exec -T web python manage.py test

    - name: Apagar contenedores
      if: always()
      run: docker compose down

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Disparar Deploy en Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"